PRODUCTS = [
    {
        "id": 1,
        "name": "iPhone 15 Pro",
        "category": "Electronics",
        "price": 999.99,
        "description": "Latest iPhone with advanced camera system",
        "image_url": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 50,
        "brand": "Apple"
    },
    {
        "id": 2,
        "name": "Samsung Galaxy S24",
        "category": "Electronics",
        "price": 899.99,
        "description": "Flagship Android smartphone",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 45,
        "brand": "Samsung"
    },
    {
        "id": 3,
        "name": "MacBook Pro 16\"",
        "category": "Electronics",
        "price": 2499.99,
        "description": "Powerful laptop for professionals",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
        "rating": 4.9,
        "stock_quantity": 25,
        "brand": "Apple"
    },
    {
        "id": 4,
        "name": "Dell XPS 13",
        "category": "Electronics",
        "price": 1299.99,
        "description": "Premium ultrabook laptop",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 30,
        "brand": "Dell"
    },
    {
        "id": 5,
        "name": "Gaming Laptop RTX 4070",
        "category": "Electronics",
        "price": 1899.99,
        "description": "High-performance gaming laptop",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 20,
        "brand": "ASUS"
    },
    {
        "id": 6,
        "name": "Sony WH-1000XM5",
        "category": "Electronics",
        "price": 399.99,
        "description": "Premium noise-cancelling headphones",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 60,
        "brand": "Sony"
    },
    {
        "id": 7,
        "name": "Apple Watch Series 9",
        "category": "Electronics",
        "price": 399.99,
        "description": "Advanced smartwatch with health features",
        "image_url": "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop",
        "rating": 4.5,
        "stock_quantity": 40,
        "brand": "Apple"
    },
    {
        "id": 8,
        "name": "Canon EOS R5",
        "category": "Electronics",
        "price": 3899.99,
        "description": "Professional mirrorless camera",
        "image_url": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop",
        "rating": 4.9,
        "stock_quantity": 15,
        "brand": "Canon"
    },
    {
        "id": 9,
        "name": "PlayStation 5",
        "category": "Electronics",
        "price": 499.99,
        "description": "Next-gen gaming console",
        "image_url": "https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 35,
        "brand": "Sony"
    },
    {
        "id": 10,
        "name": "iPad Pro 12.9\"",
        "category": "Electronics",
        "price": 1099.99,
        "description": "Professional tablet for creativity",
        "image_url": "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 55,
        "brand": "Apple"
    },
    {
        "id": 41,
        "name": "Professional Basketball",
        "category": "Sports",
        "price": 39.99,
        "description": "Official size basketball",
        "image_url": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 70,
        "brand": "Wilson"
    },
    {
        "id": 42,
        "name": "American Football",
        "category": "Sports",
        "price": 34.99,
        "description": "Official NFL football",
        "image_url": "https://images.pexels.com/photos/209841/pexels-photo-209841.jpeg?auto=compress&w=400&h=400&fit=crop",
        "rating": 4.5,
        "stock_quantity": 60,
        "brand": "Wilson"
    },
    {
        "id": 43,
        "name": "Adjustable Dumbbells",
        "category": "Sports",
        "price": 199.99,
        "description": "Set of adjustable weight dumbbells",
        "image_url": "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 25,
        "brand": "Bowflex"
    },
    {
        "id": 44,
        "name": "Yoga Mat Premium",
        "category": "Sports",
        "price": 49.99,
        "description": "Non-slip exercise yoga mat",
        "image_url": "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 85,
        "brand": "Manduka"
    },
    {
        "id": 51,
        "name": "Espresso Machine",
        "category": "Home",
        "price": 299.99,
        "description": "Automatic espresso coffee maker",
        "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 40,
        "brand": "Longhi"
    },
    {
        "id": 52,
        "name": "High-Speed Blender",
        "category": "Home",
        "price": 179.99,
        "description": "Professional blender for smoothies",
        "image_url": "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 50,
        "brand": "Vitamix"
    },
    {
        "id": 61,
        "name": "Classic White T-Shirt",
        "category": "Fashion",
        "price": 29.99,
        "description": "Comfortable cotton t-shirt",
        "image_url": "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&h=400&fit=crop",
        "rating": 4.5,
        "stock_quantity": 100,
        "brand": "Uniqlo"
    },
    {
        "id": 62,
        "name": "Summer Floral Dress",
        "category": "Fashion",
        "price": 79.99,
        "description": "Elegant floral print dress",
        "image_url": "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&h=400&fit=crop",
        "rating": 4.4,
        "stock_quantity": 75,
        "brand": "Zara"
    },
    {
        "id": 63,
        "name": "Leather Jacket",
        "category": "Fashion",
        "price": 199.99,
        "description": "Genuine leather biker jacket",
        "image_url": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 40,
        "brand": "AllSaints"
    },
    {
        "id": 64,
        "name": "Running Sneakers",
        "category": "Fashion",
        "price": 129.99,
        "description": "Lightweight running shoes",
        "image_url": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 80,
        "brand": "Nike"
    },
    {
        "id": 71,
        "name": "iPhone 15 Case Clear",
        "category": "Accessories",
        "price": 24.99,
        "description": "Transparent protective case",
        "image_url": "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop",
        "rating": 4.4,
        "stock_quantity": 200,
        "brand": "OtterBox"
    },
    {
        "id": 72,
        "name": "Samsung Galaxy Case",
        "category": "Accessories",
        "price": 19.99,
        "description": "Rugged protection case",
        "image_url": "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&w=400&h=400&fit=crop",
        "rating": 4.3,
        "stock_quantity": 150,
        "brand": "Spigen"
    },
    {
        "id": 73,
        "name": "Portable Power Bank",
        "category": "Accessories",
        "price": 39.99,
        "description": "20000mAh fast charging power bank",
        "image_url": "https://images.pexels.com/photos/4042803/pexels-photo-4042803.jpeg?auto=compress&w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 120,
        "brand": "Anker"
    },
    {
        "id": 81,
        "name": "Casual Button-Up Shirt",
        "category": "Shirts",
        "price": 49.99,
        "description": "Comfortable cotton casual shirt",
        "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop",
        "rating": 4.5,
        "stock_quantity": 85,
        "brand": "J.Crew"
    },
    {
        "id": 82,
        "name": "Polo Shirt Classic",
        "category": "Shirts",
        "price": 39.99,
        "description": "Classic fit polo shirt",
        "image_url": "https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=400&h=400&fit=crop",
        "rating": 4.4,
        "stock_quantity": 100,
        "brand": "Ralph Lauren"
    },
    {
        "id": 91,
        "name": "The Great Gatsby",
        "category": "Books",
        "price": 12.99,
        "description": "Classic American literature",
        "image_url": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
        "rating": 4.6,
        "stock_quantity": 150,
        "brand": "Penguin Classics"
    },
    {
        "id": 92,
        "name": "To Kill a Mockingbird",
        "category": "Books",
        "price": 13.99,
        "description": "Pulitzer Prize winning novel",
        "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 120,
        "brand": "Harper Lee"
    },
    {
        "id": 93,
        "name": "1984 by George Orwell",
        "category": "Books",
        "price": 14.99,
        "description": "Dystopian fiction masterpiece",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
        "rating": 4.7,
        "stock_quantity": 200,
        "brand": "Signet Classics"
    },
    {
        "id": 100,
        "name": "Steve Jobs Biography",
        "category": "Books",
        "price": 16.99,
        "description": "Authorized biography",
        "image_url": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop",
        "rating": 4.8,
        "stock_quantity": 90,
        "brand": "Simon & Schuster"
    }
] 